[package]
name = "falling-sand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace = "0.3"

rand = "0.8.5"

env_logger = "0.10"
log = "0.4"
pixels = "0.11.0"
winit = "0.27.0"
winit_input_helper = "0.13"
debug_print = "1.0.0"

[features]
# optimize = ["log/release_max_level_warn"]
# default = ["optimize"]

# For optimization (at the cost of build time)
[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = "z"
lto = "thin"
strip = true
codegen-units = 1
panic = "abort"

[profile.release.package."*"]
opt-level = "z"