//module rules;
#![allow(dead_code)]

pub const SCREEN_WIDTH: i32 = 640;
pub const SCREEN_HEIGHT: i32 = 360;
pub const SCREEN_WIDTH_USIZE: usize = SCREEN_WIDTH as usize;
pub const SCREEN_HEIGHT_USIZE: usize = SCREEN_HEIGHT as usize;
pub const SCREEN_ARRAY_LENGTH: usize = SCREEN_WIDTH_USIZE * SCREEN_HEIGHT_USIZE;
pub const SCREEN_SCALE: f32 = 2.0;

pub const CHUNK_SIZE_USIZE: usize = 64;
pub const CHUNK_LENGTH_USIZE: usize = CHUNK_SIZE_USIZE * CHUNK_SIZE_USIZE;
pub const CHUNK_SIZE_I32: i32 = CHUNK_SIZE_USIZE as i32;

// pub const SIMULATION_WIDTH_USIZE: usize = 768;
// pub const SIMULATION_HEIGHT_USIZE: usize = 488;
pub const SIMULATION_WIDTH_USIZE: usize = 100;
pub const SIMULATION_HEIGHT_USIZE: usize = 100;

pub const SIMULATION_WIDTH_I32: i32 = SIMULATION_HEIGHT_USIZE as i32;

pub const SIMULATION_HEIGHT_I32: i32 = SIMULATION_HEIGHT_USIZE as i32;
pub const SIMULATION_LENGTH: usize = SIMULATION_HEIGHT_USIZE * SIMULATION_WIDTH_USIZE;